-- 코드를 입력하세요
SELECT 
    a.CAR_ID, 
    a.CAR_TYPE, 
    ROUND(a.DAILY_FEE * 30 * (1 - b.DISCOUNT_RATE / 100), 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR a
JOIN 
    (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') b 
    ON a.CAR_TYPE = b.CAR_TYPE
WHERE 
    a.CAR_TYPE IN ('세단', 'SUV')
    AND a.CAR_ID NOT IN (
        SELECT car_id 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' 
          AND START_DATE < '2022-12-01'
    )
GROUP BY 
    a.CAR_ID
HAVING 
    FEE BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, 
    a.CAR_TYPE ASC, 
    a.CAR_ID DESC;